Remove banner ad at bottom on namu.wiki
List-KR/List-KR pull request #235
Opened 2022-03-13 06:37 UTC by seia-soto

Adds banner ad after the content area on namu.wiki.

Adding rule from:

- https://github.com/yous/YousList/pull/212#issuecomment-1065946899

Tested on ungoogled-chromium on macOS with AdGuard Web.

![image](https://user-images.githubusercontent.com/30369714/158048328-5801b352-5e7c-4a3a-ae96-ca6840b13df4.png)

2022-03-13 06:39 UTC, seia-soto commented
Requesting review to learn the general contribution norm of this repository.

Please, suggest any improvement on this PR.

2022-03-13 06:42 UTC, piquark6046 requested changes
Please move your rule to top of the file.

2022-03-13 07:40 UTC, piquark6046 approved these changes

2022-03-13 07:40 UTC, merged

2022-03-13 08:47 UTC, seia-soto commented
> Please move your rule to top of the file.

I was late, due to fixed schedule at this time. By seeing the blame graph, I can see that newer rules go to top in this project. Is this right?

https://github.com/List-KR/List-KR/blame/master/filters/extended_css.txt

2022-03-13 08:51 UTC, piquark6046 commented
https://github.com/List-KR/List-KR/pull/235#issuecomment-1066054516
Yes, A new rule must be located in top of a section or a file.

2022-03-14 13:43 UTC, PraeconiumMercatoriumInterclusio commented
Remove banner ad(a.k.a Power Link) at bottom on namu.wiki by adguard
||namu.wiki^$domain=namu.wiki
@@namu.wiki/*/$domain=namu.wiki

ygosu.com
||ygosu.com^$domain=ygosu.com
@@ygosu.com/*/$domain=ygosu.com

2022-03-14 13:44 UTC, PraeconiumMercatoriumInterclusio commented
> Remove banner ad(a.k.a Power Link) at bottom on namu.wiki ||namu.wiki^$domain=namu.wiki ||namu.wiki^$domain=namu.wiki
> 
> ygosu.com ||ygosu.com^$domain=ygosu.com [@](https://arca.live/u/@)@ygosu.com/*/$domain=ygosu.com