Useful filters
List-KR/List-KR pull request #344
Opened 2022-05-15 15:04 UTC by seia-soto

From the issue #335 , I think it's reasonable to accept the possible enhancement from the dialogs. To make List-KR better place, I understand that similar problem can be raised in future just like [the comment](https://github.com/List-KR/List-KR/issues/335#issuecomment-1126736851) from [@rlfehd7915](https://github.com/rlfehd7915) and want to add useful ad filter version to the repository.

## How

We'll add a file to describe the useful ads on various websites. Useful ad filters are separated from allowlist in this repository since the purpose is different. For additional information, please see the file content.

```
! The intend of this filter is different from allowlist.txt.
! This purpose of this filter is to unblock useful filters or self-promotion on the website, not to fix the invalid or incorrect blocking exception.
!
! + Also, unblocking doesn't affect to the capability of the adblockers generally, so splitting versions per adblocker will be useless effort.
! + To make things clear, appending issue URL or simple information before adding the line is appreciated.
```

## Disadvantages

1. AdGuard applications are always asking users to choose if they want to add useful ads filter. However, List-KR won't be added and handled by default in this option.

> I am sorry that I cannot do make any improvements to this problem by default.

2. We need more man-power to maintain the useful ads.

> Instead of constantly maintaining the useful ads filter, we have two options that can be used. (Note that I am accepting the second solution)
> 1. Make List-KR_Useful completely separated from List-KR, so users will add two filters in total if they want. (one is List-KR, another is List-KR useful)
> 2. Make merged version of useful ads filter, so users will add only one filter at all.

2022-05-15 15:11 UTC, piquark6046 reviewed
Why not just allowing them?
Example: List-KR filter + List-KR Useful filter (Not making one unified filter)

2022-05-15 15:14 UTC, seia-soto commented
Because the element in the case of #335 is identified as ad. In viewpoint of me, 1) it's irrelative element to the website 2) it's kind of self-promotion 3) we need to give option to users to choose if they want to block all kind of ads.

2022-05-15 15:16 UTC, seia-soto commented
> Why not just allowing them? Example: List-KR filter + List-KR Useful filter (Not making one unified filter)

So, you're saying like the following if you mind is changes?

1. Make List-KR_Useful completely separated from List-KR, so users will add two filters in total if they want. (one is List-KR, another is List-KR useful)

2022-05-15 15:22 UTC, seia-soto commented
This can be rejected at any time due to effortless option, just feel free to leave your opinion to this, to participants and contributors, users.

2022-05-15 15:25 UTC, piquark6046 reviewed
I meant what about making List-KR Useful filter contains allowing rules like `#@#`, `#@?#`, `$badfilter` and `#@%#`.

If there is a sponsored advertisement, List-KR maintainers write a blocking rule in List-KR and an allowing rule in List-KR Useful.

Filename | Content
--------- | ---------
filters-share/specific_ELEMHIDE.txt | `###advertisement`
filters-share/specific_ELEMHIDE.txt | `###sponsored`
filters-share/useful/specific_ELEMHIDE.txt | `#@##sponsored`

2022-05-15 15:25 UTC, piquark6046 commented on filter_Useful.txt
> +!#endif
```suggestion
!#include filters-share/useful/adservice.txt
!#include filters-share/useful/adservice_firstparty.txt
!#include filters-share/useful/general_elemhide.txt
!#include filters-share/useful/general_url.txt
!#include filters-share/useful/specific_URL.txt
!#include filters-share/useful/specific_ELEMHIDE.txt
!#include filters-share/useful/allowlist.txt

!#if (adguard_ext_firefox || adguard_app_windows || adguard_app_mac || adguard_app_android || adguard_ext_chromium || adguard_ext_edge)
!#include filters-AG/useful/allowlist_stealth.txt
!#endif

!#if (!adguard_ext_android_cb)
!#include filters-share/useful/specific_CSS.txt
!#include filters-share/useful/extended_css_ELEMHIDE.txt
!#include filters-share/useful/extended_css_INJECTION.txt
!#include filters-AG/useful/extended_css_ELEMHIDE.txt
!#include filters-AG/useful/extended_css_INJECTION.txt
!#include filters-AG/useful/scriptlets.txt
!#include filters-share/useful/lkscriptlet.txt
!#include filters-share/useful/javascript.txt
!#include filters-AG/useful/antiadblock.txt
!#endif

!#if (!adguard_app_ios && !adguard_ext_safari)
!#include filters-AG/useful/specific_REDIRECT.txt
!#endif

!#if (adguard_ext_android_cb)
!#include filters-AG/useful/contentblocker.txt
!#endif

!#if (adguard_ext_firefox || adguard_app_windows || adguard_app_mac || adguard_app_android)
!#include filters-AG/useful/html_filtering.txt
!#endif

!#if (adguard_app_windows || adguard_app_mac || adguard_app_android || adguard_ext_firefox || adguard_ext_chromium || adguard_ext_edge )
!#include filters-share/useful/removeparam.txt
!#endif

!#if (adguard_app_android)
!#include filters-AG/useful/mobile/android/allowlist_android_app.txt
!#include filters-AG/useful/mobile/android/android_app.txt
!#include filters-AG/useful/mobile/android/android_specific.txt
!#include filters-AG/useful/mobile/android/antiadblock_android_app.txt
!#include filters-AG/useful/mobile/android/allowlist_stealth_android_app.txt
!#endif

!#if (adguard_app_ios)
!#include filters-AG/useful/mobile/ios/allowlist_ios_app.txt
!#include filters-AG/useful/mobile/ios/antiadblock_ios_app.txt
!#include filters-AG/useful/mobile/ios/ios_app.txt
!#include filters-AG/useful/mobile/ios/ios_specific.txt
!#endif

!#if (adguard_app_windows)
!#include filters-AG/useful/desktop/windows_app/allowlist_stealth.txt
!#include filters-AG/useful/desktop/windows_app/allowlist.txt
!#include filters-AG/useful/desktop/windows_app/antiadblock.txt
!#include filters-AG/useful/desktop/windows_app/specific_URL.txt
!#endif

!#if (adguard_app_mac)
!#include filters-AG/useful/desktop/macos_app/allowlist_stealth.txt
!#include filters-AG/useful/desktop/macos_app/allowlist.txt
!#include filters-AG/useful/desktop/macos_app/antiadblock.txt
!#include filters-AG/useful/desktop/macos_app/specific_URL.txt
!#endif
```

2022-05-15 15:25 UTC, piquark6046 commented on filter_Useful-uBO.txt
> +!#include filters-share/removeparam.txt
```suggestion
!#include filters-share/useful/adservice.txt
!#include filters-share/useful/adservice_firstparty.txt
!#include filters-share/useful/general_elemhide.txt
!#include filters-share/useful/general_url.txt
!#include filters-share/useful/specific_URL.txt
!#include filters-share/useful/specific_ELEMHIDE.txt
!#include filters-share/useful/allowlist.txt

!#include filters-share/useful/extended_css_ELEMHIDE.txt
!#include filters-share/useful/extended_css_INJECTION.txt
!#include filters-uBO/useful/specific_REDIRECT.txt
!#include filters-uBO/useful/extended_css_ELEMHIDE.txt
!#include filters-uBO/useful/extended_css_INJECTION.txt
!#include filters-uBO/useful/scriptlets.txt
!#include filters-share/useful/lkscriptlet.txt
!#include filters-share/useful/javascript.txt
!#include filters-uBO/useful/antiadblock.txt

!#if cap_user_stylesheet
!#include filters-share/useful/specific_CSS.txt
!#endif

!#if cap_html_filtering
!#include filters-uBO/useful/html_filtering.txt
!#endif

!#include filters-share/useful/removeparam.txt
```

2022-05-15 15:27 UTC, piquark6046 requested changes

2022-05-15 15:27 UTC, piquark6046 commented on filter_Useful-uBO.txt
> +! Description: List-KR for uBlock Origin
The duplicated title and description.
```suggestion
! Title: List-KR Useful uBO
! Description: List-KR Useful for uBlock Origin
```

2022-05-15 15:27 UTC, piquark6046 commented on filter_Useful.txt
> +! Description: List-KR for AdGuard
The duplicated title and description.
```suggestion
! Title: List-KR Useful
! Description: List-KR Useful for AdGuard
```

2022-05-16 00:02 UTC, green1052 commented
> I meant what about making List-KR Useful filter contains allowing rules like `#@#`, `#@?#`, `$badfilter` and `#@%#`.
> 
> If there is a sponsored advertisement, List-KR maintainers write a blocking rule in List-KR and an allowing rule in List-KR Useful.
> 
> Filename	Content
> filters-share/specific_ELEMHIDE.txt	`###advertisement`
> filters-share/specific_ELEMHIDE.txt	`###sponsored`
> filters-share/useful/specific_ELEMHIDE.txt	`#@##sponsored`

^

i think better

2022-05-16 00:56 UTC, seia-soto commented
Yes, it's more structured than my solution originally. However, by looking at the amount of useful ads filter, it's also reasonable to keep it in one file. Longer term, I agree with you.

2022-05-16 06:53 UTC, seia-soto commented
@piquark6046 Just a confirmation about `filters-share/useful/category.txt`.

Do you mind adding `filters-[PLATFORM]/useful/category.txt` for e.g. `filters-AG/useful/category.txt`?

2022-05-16 08:27 UTC, piquark6046 commented
> Do you mind adding filters-[PLATFORM]/useful/category.txt for e.g. filters-AG/useful/category.txt?
> 
Yeap.

>  I think it's not required since unblocking rules do not affected by adblocker capabilities.
>
Then, will you separate into the each categorizes. If lines of List-KR Useful are too large to manage in a single file?

2022-05-16 14:26 UTC, seia-soto commented
I applied your improvements on my PR.

2022-05-16 14:45 UTC, piquark6046 reviewed
I meat that I want to leave just `filters-[PLATFORM]/useful/[category]`.

2022-05-17 13:09 UTC, seia-soto commented
@piquark6046 😅 Can you describe in detail on Slack if you expect your description would be long? I thought you want to make dedicated useful filters per ad blocker platforms and categories.

2022-05-17 13:15 UTC, piquark6046 commented
https://github.com/List-KR/List-KR/pull/344#issuecomment-1128849621
Hmm... In the other word, I want to add an allowing rules like `UsefulAdsFilter/sections/usefulads.txt` in AdguardFilters.

2022-05-17 13:18 UTC, seia-soto commented
Thanks for straight forwarding. I'll look at it first and make changes to be reviewed. Also, got a suggestion adding comments(`!`) to empty files from @green1052 .

2022-05-17 13:24 UTC, piquark6046 commented
> Also, got a suggestion adding comments(!) to empty files
>
Yeap. If the version of AdGuard Browser Extension is outdated, AdGuard will crash.
https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1999

2022-05-21 09:10 UTC, closed without merging

2022-05-21 09:23 UTC, seia-soto commented
I'll postpone this work as there is no issue that requiring this to be forced right now. Also, I think we need to discuss about it more.