dcinside.com - Ad
List-KR/List-KR pull request #345
Opened 2022-05-16 11:27 UTC by QiAnCeNo

2022-05-16 13:32 UTC, piquark6046 requested changes
@QiAnCeNo Can you give me the URLs?
If the URLs have to be private, please email me.

2022-05-16 13:38 UTC, QiAnCeNo commented
> 
https://www.dcinside.com/
https://m.dcinside.com/

https://gall.dcinside.com/board/lists/?id=baseball_new10
https://m.dcinside.com/board/baseball_new10

You can check them out at these URLS.

2022-05-16 14:14 UTC, piquark6046 commented
@Raiden-Ei @seia-soto 
Do you think that List-KR blocks the following elements?

<details>
<summary>Screenshot</summary>

![asdaf](https://user-images.githubusercontent.com/98787049/168613016-be6914dc-ab0c-418a-8f13-7336666eb027.png)


</details>

2022-05-16 14:18 UTC, piquark6046 reviewed
I don't want to add your changes to block the annoyances elements.

2022-05-16 14:26 UTC, QiAnCeNo commented
> I don't want to add your changes to block the annoyances elements.

Another maintainer, @seia-soto said that content which unrelated site should be blocked. https://github.com/List-KR/List-KR/issues/335#issuecomment-1126953986
If so I want to block this element because it is not related with the site.

2022-05-16 14:27 UTC, green1052 commented
> I don't want to add your changes to block the annoyances elements.

i agree your comment

2022-05-16 14:33 UTC, piquark6046 commented
https://github.com/List-KR/List-KR/pull/345#issuecomment-1127745464
> If so I want to block this element because it is not related with the site.
>
However, dcinside wiki and dcnews is related to dcinside community because they are held by DCinside Corp.

2022-05-16 14:35 UTC, QiAnCeNo commented
> [#345 (comment)](https://github.com/List-KR/List-KR/pull/345#issuecomment-1127745464)
> 
> > If so I want to block this element because it is not related with the site.
> 
> However, dcinside wiki and dcnews is related to dcinside community because they are held by DCinside Corp.

arca.live and namu.news as mentioned in a previous comment are also held by the same company.

2022-05-16 14:40 UTC, green1052 commented
나무뉴스의 경우는 다른 뉴스사의 뉴스를 가져오는 것이기 때문에 아카라이브의 연관이 없다고 생각됩니다.

하지만 디시인사이드에 경우에는 유저가 직접 작성하는 디시위키 등 연관이 있다, 생각하여 차단하지 않는 것이 바르다고 생각됩니다.

2022-05-16 14:42 UTC, green1052 commented
또 한가지 예를 들자면 나무위키 네비바에는 아카라이브 항목이 있습니다.

나무위키와 연관이 없지만 차단하지 않는 이유와 같습니다.

2022-05-16 14:45 UTC, QiAnCeNo commented
> 나무뉴스의 경우는 다른 뉴스사의 뉴스를 가져오는 것이기 때문에 아카라이브의 연관이 없다고 생각됩니다.
> 
> 하지만 디시인사이드에 경우에는 유저가 직접 작성하는 디시 키위 등 연관이 된다 생각하여 차단하지 않는 것이 바르다 생각됩니다.

디시인사이드는 도메인부터 다른 https://dcnewsj.joins.com/ 중앙일보 사이트로 넘어가고 디시미디어, 디시이슈도 입점한 다른 언론사에서 작성합니다.

2022-05-16 14:47 UTC, QiAnCeNo commented
> 또 한가지 예를 들자면 나무위키 네비바에는 아카라이브 항목이 있습니다.
> 
> 나무위키와 연관이 없지만 차단하지 않는 이유와 같습니다.

https://namu.news/ 나무뉴스에서 나무위키, 아카라이브 링크가 메뉴바에 있습니다.

2022-05-16 14:52 UTC, green1052 commented
> > 또 한가지 예를 들자면 나무위키 네비바에는 아카라이브 항목이 있습니다.
> > 나무위키와 연관이 없지만 차단하지 않는 이유와 같습니다.
> 
> https://namu.news/ 나무뉴스에서 나무위키, 아카라이브 링크가 메뉴바에 있습니다.

디시인사이드의 디시이슈, 디시 미디어 사이드바 항목에도 디시인사이드로 통하는 아이템이 있습니다.

2022-05-16 14:56 UTC, QiAnCeNo commented
> > > 또 한가지 예를 들자면 나무위키 네비바에는 아카라이브 항목이 있습니다.
> > > 나무위키와 연관이 없지만 차단하지 않는 이유와 같습니다.
> > 
> > 
> > https://namu.news/ 나무뉴스에서 나무위키, 아카라이브 링크가 메뉴바에 있습니다.
> 
> 디시인사이드의 디시이슈, 디시 미디어 사이드바 항목에도 디시인사이드로 통하는 아이템이 있습니다.

https://github.com/List-KR/List-KR/issues/335#issuecomment-1126953986 를 확인해주세요.

2022-05-16 15:47 UTC, seia-soto commented
@QiAnCeNo 지금 상황을 읽어보니 방해 요소와 광고 간의 차이점이 대두되고 있는 듯 싶은데 이에 대한 정확한 기준을 확립하길 원하시는 듯 싶은데 이전 발언에 대해서 모든 경우에 적용하지 않고 새로운 기준을 확립하는 것에 대해 어떻게 생각하시나요? 단, 제가 제 말을 취소한다는 것같은 늬앙스 자체가 굉장히 혼란을 줄 수 있다고 생각되며 이에 대해서는 정말 죄송하게 생각합니다.
> 다만 이후에도 저희가 규칙을 정확히 하더라도 비슷한 일은 굉장히 빈번하게 일어날 수 있고 과소 혹은 과도한 차단이 될 수 있어 사견의 개입을 완전히 막자는 뜻은 아닙니다.

2022-05-16 15:48 UTC, seia-soto commented
제 이전 댓글을 포함하시는 것의 여부와 상관없이 견해를 들려주시면 정말 감사하겠습니다.

2022-05-16 16:33 UTC, QiAnCeNo commented
> 제 이전 댓글을 포함하시는 것의 여부와 상관없이 견해를 들려주시면 정말 감사하겠습니다.

https://github.com/List-KR/List-KR/issues/335#issuecomment-1126953986 에서 제시하신 기준으로는 검색 서비스가 메인인 다음(daum.net)의 첫 페이지 뉴스도 시각에 따라서는 광고라고 볼 수도 있습니다.
뉴스는 같은 도메인을 사용하므로 같은 서비스라고 보는 시각도 있을 수 있겠지만 서비스 도메인이 다른 카카오TV 등의 광고 배너는 어떨까요?
PC 다음에서 검색하면 사이드바에 노출되는 같이가치 추천글도 카카오 도메인에서 서비스되고 있습니다.

이전에 제시하신 광고는 광고일 뿐이라는 논리대로라면 대부분의 서비스에서 주 기능 이외의 기능이 모두 차단 대상이 될 수 있기 때문에 객관적이고 명확한 기준이 필요하다고 생각합니다.

단순히 도메인이 다른 것으로 구분하면 네이버 쇼핑판을 소개하거나 네이버 쇼핑을 홍보하는 경우는 같은 도메인입니다.
주요기능이 아닌 부가적인 서비스를 홍보하는 것이라면 애드가드 홈페이지(adguard.com)에서 애드가드 VPN을 홍보하는 것도 광고라고 판단할 수 있습니다.
기준은 간단한 문제가 아니며 다른 리스트들의 사례와 기준도 참고해가며 만들어 나가야할 것입니다.

2022-05-17 02:59 UTC, seia-soto commented
> > 제 이전 댓글을 포함하시는 것의 여부와 상관없이 견해를 들려주시면 정말 감사하겠습니다.
> 
> 
> 
> https://github.com/List-KR/List-KR/issues/335#issuecomment-1126953986 에서 제시하신 기준으로는 검색 서비스가 메인인 다음(daum.net)의 첫 페이지 뉴스도 시각에 따라서는 광고라고 볼 수도 있습니다.
> 
> 뉴스는 같은 도메인을 사용하므로 같은 서비스라고 보는 시각도 있을 수 있겠지만 서비스 도메인이 다른 카카오TV 등의 광고 배너는 어떨까요?
> 
> PC 다음에서 검색하면 사이드바에 노출되는 같이가치 추천글도 카카오 도메인에서 서비스되고 있습니다.
> 
> 
> 
> 이전에 제시하신 광고는 광고일 뿐이라는 논리대로라면 대부분의 서비스에서 주 기능 이외의 기능이 모두 차단 대상이 될 수 있기 때문에 객관적이고 명확한 기준이 필요하다고 생각합니다.
> 
> 
> 
> 단순히 도메인이 다른 것으로 구분하면 네이버 쇼핑판을 소개하거나 네이버 쇼핑을 홍보하는 경우는 같은 도메인입니다.
> 
> 주요기능이 아닌 부가적인 서비스를 홍보하는 것이라면 애드가드 홈페이지(adguard.com)에서 애드가드 VPN을 홍보하는 것도 광고라고 판단할 수 있습니다.
> 
> 기준은 간단한 문제가 아니며 다른 리스트들의 사례와 기준도 참고해가며 만들어 나가야할 것입니다.

지금 이 PR을 생성하시면서 제 이전 의견을 참조하셨는데 동시에 기준 자체가 명확하지 않다고 판단하신 것으로 보입니다. 그렇다면 새 기준은 어떻게 나누는 것이 적합하다고 판단하시나요? 이미 방해 요소와 광고 등 많은 필터들이 물론 존재합니다. 그럼에도 불구하고 각각을 판단하는 기준은 여전히 개인적입니다. 하지만 지금과 같은 일이 발생하지 않는 이유는 보통의 경우에는 불편함을 야기하는 경우에 필터에 추가되는 경우가 대다수이기 때문이라고 생각합니다. 지금 생성하신 PR의 경우에는 특정한 의도를 가지고 계신 듯하여 다시 정확히 어떤 기준을 원하시는지 여쭈어보고 싶습니다.

그리고 한 가지 제가 명확하게 느낄 수 있는
점은 현재 제시해주신 차단 규칙이 굉장히 과하게 느껴진다는 것입니다. 이전 기회에서 유용한 광고 필터도 추가될 수 있도록 하고 향상될 수 있는 경우 향상시키기 위해 노력할 것이니 솔직한 피드백을 들려주시고 협조해주시면 감사하겠습니다.

단, 기본적으로는 현재 최종 결정자이기도 한 @piquark6046 님의 정책을 따라 List-KR에서는 다음과 같은 사항은 그대로 지켜질 수 있도록 해주십시오.
- List-KR은 방해 요소나 추적기 등이 아닌 광고만을 차단합니다.

2022-05-17 03:03 UTC, seia-soto commented
그리고 강조를 위해 다시 한 번 밝히지만 정확한 기준은 말씀하신대로 성립하기에는 쉽지 않고 저는 여전히 더 많은 경우를 위해 기본적으로 광고만을 차단한다는 전제 아래 유연하게 대응할 수 있는 입장을 고수할 것입니다.

2022-05-17 05:28 UTC, QiAnCeNo commented
> > > 제 이전 댓글을 포함하시는 것의 여부와 상관없이 견해를 들려주시면 정말 감사하겠습니다.
> > 
> > 
> > [#335 (comment)](https://github.com/List-KR/List-KR/issues/335#issuecomment-1126953986) 에서 제시하신 기준으로는 검색 서비스가 메인인 다음(daum.net)의 첫 페이지 뉴스도 시각에 따라서는 광고라고 볼 수도 있습니다.
> > 뉴스는 같은 도메인을 사용하므로 같은 서비스라고 보는 시각도 있을 수 있겠지만 서비스 도메인이 다른 카카오TV 등의 광고 배너는 어떨까요?
> > PC 다음에서 검색하면 사이드바에 노출되는 같이가치 추천글도 카카오 도메인에서 서비스되고 있습니다.
> > 이전에 제시하신 광고는 광고일 뿐이라는 논리대로라면 대부분의 서비스에서 주 기능 이외의 기능이 모두 차단 대상이 될 수 있기 때문에 객관적이고 명확한 기준이 필요하다고 생각합니다.
> > 단순히 도메인이 다른 것으로 구분하면 네이버 쇼핑판을 소개하거나 네이버 쇼핑을 홍보하는 경우는 같은 도메인입니다.
> > 주요기능이 아닌 부가적인 서비스를 홍보하는 것이라면 애드가드 홈페이지(adguard.com)에서 애드가드 VPN을 홍보하는 것도 광고라고 판단할 수 있습니다.
> > 기준은 간단한 문제가 아니며 다른 리스트들의 사례와 기준도 참고해가며 만들어 나가야할 것입니다.
> 
> 지금 이 PR을 생성하시면서 제 이전 의견을 참조하셨는데 동시에 기준 자체가 명확하지 않다고 판단하신 것으로 보입니다. 그렇다면 새 기준은 어떻게 나누는 것이 적합하다고 판단하시나요? 이미 방해 요소와 광고 등 많은 필터들이 물론 존재합니다. 그럼에도 불구하고 각각을 판단하는 기준은 여전히 개인적입니다. 하지만 지금과 같은 일이 발생하지 않는 이유는 보통의 경우에는 불편함을 야기하는 경우에 필터에 추가되는 경우가 대다수이기 때문이라고 생각합니다. 지금 생성하신 PR의 경우에는 특정한 의도를 가지고 계신 듯하여 다시 정확히 어떤 기준을 원하시는지 여쭈어보고 싶습니다.
> 
> 그리고 한 가지 제가 명확하게 느낄 수 있는 점은 현재 제시해주신 차단 규칙이 굉장히 과하게 느껴진다는 것입니다. 이전 기회에서 유용한 광고 필터도 추가될 수 있도록 하고 향상될 수 있는 경우 향상시키기 위해 노력할 것이니 솔직한 피드백을 들려주시고 협조해주시면 감사하겠습니다.
> 
> 단, 기본적으로는 현재 최종 결정자이기도 한 @piquark6046 님의 정책을 따라 List-KR에서는 다음과 같은 사항은 그대로 지켜질 수 있도록 해주십시오.
> 
> * List-KR은 방해 요소나 추적기 등이 아닌 광고만을 차단합니다.

불편함으로 기준으로 하기 때문에 문제가 없었다라고 하셨지만 그것이 잘못된 차단이라는 이슈가 있었습니다.(https://github.com/List-KR/List-KR/issues/335) 하지만  해당 댓글에서 서비스를 잘 사용하지 않아서 모르지만 광고는 광고다라는 의견으로 잘못된 차단이 아니라는 의견을 내셨습니다.
잘 사용하지 않아서 모르지만 불편함을 느끼셨다는 걸까요?
또한 이 차단 규칙이 과하게 느껴진다고 하시기엔 제시해주신 기준으로는 동일하며 모바일 첫페이지, PC 첫페이지, 모바일 게시판 페이지, PC 게시판 페이지의 코드가 모두 분리되어 있어 줄 수가 많아 진 것 뿐입니다.

제시한 기준으로 적용을 해야한다면 저는 이 커밋이 적용되어야한다 생각하며 여기서 더 나아가 다른 서비스들에서도 역시 점차적으로 추가할 예정입니다.

광고와 방해요소를 구분하는 새 기준에 대해서는 위의 제가 남긴 코멘트에서 작성한 바와 같이 간단히 정의할 수 있는 문제가 아닙니다. 방해요소를 차단한다면 명확하고 객관적이 기준이 생겨야한다는 의견이며, 기본적으로 광고만을 차단한다는 기준하에 유연하게 적용하기 위함이라 하셨지만 @seia-soto 님의 광고는 광고다라는 기준이 있는 한 방해요소들 역시 광고로 취급될 것 입니다.

2022-05-17 05:31 UTC, seia-soto commented
@QiAnCeNo 저는 지금 제 발화의 문제점을 이해하고 기준을 개선하기 위해 의견을 여쭈어본 것이지 제 의견을 맹목적으로 따른 해석을 부탁드리지 않았습니다. 다시 피드백을 남겨주시겠습니까? 저는 현재 문제점을 인식하고 개선을 위해 의견을 듣고 싶습니다.

2022-05-17 05:34 UTC, seia-soto commented
어떤 점에서 불만 사항이 심화되셨는지 제가 물론 단번에 제대로 파악하기는 쉽지 않을겁니다. 다만 단순히 가지고 계신 불만 사항을 제가 말한 의견, 심지어 현재 사안에서 문제를 인식하신 의견을 지속적으로 인용하며 맹목적인 요소 차단으로 표현하시는 것은 옳지 않다고 생각하며 이는 단순히 레포지토리에 대한 공격으로 인식될 뿐입니다.

2022-05-17 05:50 UTC, QiAnCeNo commented
> 어떤 점에서 불만 사항이 심화되셨는지 제가 물론 단번에 제대로 파악하기는 쉽지 않을겁니다. 다만 단순히 가지고 계신 불만 사항을 제가 말한 의견, 심지어 현재 사안에서 문제를 인식하신 의견을 지속적으로 인용하며 맹목적인 요소 차단으로 표현하시는 것은 옳지 않다고 생각하며 이는 단순히 레포지토리에 대한 공격으로 인식될 뿐입니다.

제시해주신 기준에 따르는 것이 공격이라 느껴지셨다니 안타까울 뿐입니다.
이것이 공격이라 생각하신다면 레포에 공격한 것이 본인이라는 뜻 밖에 되지않습니다.

2022-05-17 08:39 UTC, seia-soto commented
> > 어떤 점에서 불만 사항이 심화되셨는지 제가 물론 단번에 제대로 파악하기는 쉽지 않을겁니다. 다만 단순히 가지고 계신 불만 사항을 제가 말한 의견, 심지어 현재 사안에서 문제를 인식하신 의견을 지속적으로 인용하며 맹목적인 요소 차단으로 표현하시는 것은 옳지 않다고 생각하며 이는 단순히 레포지토리에 대한 공격으로 인식될 뿐입니다.
> 
> 
> 
> 제시해주신 기준에 따르는 것이 공격이라 느껴지셨다니 안타까울 뿐입니다.
> 
> 이것이 공격이라 생각하신다면 레포에 공격한 것이 본인이라는 뜻 밖에 되지않습니다.

저도 그렇게 생각하셨다면 유감스럽게 생각합니다. 다시 한 번 저는 그 기준을 개선할 수 있도록 협조를 요청하는 바입니다. 그렇지 않으면 제 생각과 상관없이 앞으로도 비슷한 일이 일어날 것입니다.

2022-05-17 13:26 UTC, QiAnCeNo commented
> > > 어떤 점에서 불만 사항이 심화되셨는지 제가 물론 단번에 제대로 파악하기는 쉽지 않을겁니다. 다만 단순히 가지고 계신 불만 사항을 제가 말한 의견, 심지어 현재 사안에서 문제를 인식하신 의견을 지속적으로 인용하며 맹목적인 요소 차단으로 표현하시는 것은 옳지 않다고 생각하며 이는 단순히 레포지토리에 대한 공격으로 인식될 뿐입니다.
> > 
> > 
> > 제시해주신 기준에 따르는 것이 공격이라 느껴지셨다니 안타까울 뿐입니다.
> > 이것이 공격이라 생각하신다면 레포에 공격한 것이 본인이라는 뜻 밖에 되지않습니다.
> 
> 저도 그렇게 생각하셨다면 유감스럽게 생각합니다. 다시 한 번 저는 그 기준을 개선할 수 있도록 협조를 요청하는 바입니다. 그렇지 않으면 제 생각과 상관없이 앞으로도 비슷한 일이 일어날 것입니다.

방해요소를 광고로 선언한건 제가 아니다보니, 제가 뭐라 나설 수 있는 부분이 아닌 것 같습니다.
광고는 광고다라고 의견을 주신 것을 철회하는 것이 아니라면, 그 의견에 대해 얘기하는 것을 공격이라 표현하지 마시고, 왜 이 커밋이 기존 의견과 다른 과도한 커밋인지 부연 설명을 부탁드립니다.

2022-05-17 13:45 UTC, seia-soto commented
@QiAnCeNo 저는 의견을 이야기하는 것을 공격이라 표현한 것이 아니라 제 이전 주장에 동의하시지 않는 것 같으니 해당 부분에 대해 어떤 점을 개선할 수 있을지 여쭈어본 것입니다. 제가 표현한 공격이라 함은 제 기존 주장을 마음에 들어하시지 않음에도 불구하고 개선점을 이야기하고 해결을 위해 같이 나아가는 것이 아니라 맹목적으로 개선 의지를 무시하고 의도적으로 필터를 수정하는 행동을 말합니다. 언제나 문장으로는 지금 정확히 어떤 방향을 개선을 하시고 싶어하시는지 정확히 알 수가 없으므로 직접적으로 제시를 부탁드렸었습니다. 이건 제 의견과 상관없이 충분히 제시가 가능하시다고 생각을 합니다.

다시 말씀드립니다. 저는 지금 제 이전 의견이 당연히 완벽하지 못하다 생각을 하여서 계속해서 의견을 여쭈어보고 있는데 단순히 저와 이전 주장들을 굴복시킬 생각을 하지 마시고 협조적으로 나오시길 부탁드립니다. 단순히 마음이 들지 않으시기 때문에 이전 주장의 철회 등에만 집중하여 일의 진행을 막지 말으시고 직접적인 해결책을 제시하여 커뮤니티가 더 좋은 방향을 나아갈 수 있도록 해주십시오.

지금 제시하시는 해결 방식으로는 실질적으로 시간을 낭비하는 것이 더 크니 지속적으로 동일한 태도로 나오시는 경우에는 죄송하지만 더 이상 이 건을 다루지 않도록 하겠습니다.

2022-05-17 13:55 UTC, QiAnCeNo commented
> @QiAnCeNo 저는 의견을 이야기하는 것을 공격이라 표현한 것이 아니라 제 이전 주장에 동의하시지 않는 것 같으니 해당 부분에 대해 어떤 점을 개선할 수 있을지 여쭈어본 것입니다. 제가 표현한 공격이라 함은 제 기존 주장을 마음에 들어하시지 않음에도 불구하고 개선점을 이야기하고 해결을 위해 같이 나아가는 것이 아니라 맹목적으로 개선 의지를 무시하고 의도적으로 필터를 수정하는 행동을 말합니다. 언제나 문장으로는 지금 정확히 어떤 방향을 개선을 하시고 싶어하시는지 정확히 알 수가 없으므로 직접적으로 제시를 부탁드렸었습니다. 이건 제 의견과 상관없이 충분히 제시가 가능하시다고 생각을 합니다.
> 
> 다시 말씀드립니다. 저는 지금 제 이전 의견이 당연히 완벽하지 못하다 생각을 하여서 계속해서 의견을 여쭈어보고 있는데 단순히 저와 이전 주장들을 굴복시킬 생각을 하지 마시고 협조적으로 나오시길 부탁드립니다. 단순히 마음이 들지 않으시기 때문에 이전 주장의 철회 등에만 집중하여 일의 진행을 막지 말으시고 직접적인 해결책을 제시하여 커뮤니티가 더 좋은 방향을 나아갈 수 있도록 해주십시오.
> 
> 지금 제시하시는 해결 방식으로는 실질적으로 시간을 낭비하는 것이 더 크니 지속적으로 동일한 태도로 나오시는 경우에는 죄송하지만 더 이상 이 건을 다루지 않도록 하겠습니다.

새로운 의견을 시작한건 제가 아니라 @seia-soto 님 이십니다. 본인의 의견에 대해 얘기를 하는 것인데, 이런 부분이 대해서는 쉽게 기준을 내릴 수 있는 것이 아니다라고 수차례 얘기한 사람에게 본인의 의견을 보완하라는 건 조금 당황스러운 얘기네요.
기존 의견의 기준에서 이 커밋이 왜 다른지 설명 주시는게 어려운 일일까요?

2022-05-17 14:01 UTC, seia-soto commented
저는 제가 정확히 파악하지도 못한 상태의 @QiAnCeNo 님의 의견을 보완하시라고 말한 적이 없습니다. 기준을 쉽게 내릴 수 없다고 말씀하셨고 저 또한 제 의견이 완벽하지 않을 수 있다고 인정하며 이에 대해서 어떻게 개선을 하면 좋을지 의견을 여쭈었던 것입니다. 불필요한 언사를 더 만들어지 말아주시고 해결을 위해 노력해주시기 바랍니다.

2022-05-17 14:02 UTC, QiAnCeNo commented
> 저는 제가 정확히 파악하지도 못한 상태의 @QiAnCeNo 님의 의견을 보완하시라고 말한 적이 없습니다. 기준을 쉽게 내릴 수 없다고 말씀하셨고 저 또한 제 의견이 완벽하지 않을 수 있다고 인정하며 이에 대해서 어떻게 개선을 하면 좋을지 의견을 여쭈었던 것입니다. 불필요한 언사를 더 만들어지 말아주시고 해결을 위해 노력해주시기 바랍니다.

불필요한 언사를 누가 지속하는지 모르겠네요. 기존 의견과 이 커밋은 뭐가 다르다 라는 걸 얘기만 해주시면됩니다.

2022-05-17 14:04 UTC, seia-soto commented
저는 이미 제 이전 기준이 완벽하지 않다라고 생각합니다. 그래서 원하시는데로 기존 의견과 이 커밋이 전혀 충돌점이 없음에도 불구하고 당장 받아들여지지 않을 예정입니다. 말씀하시는 과정은 불필요한 과정입니다.

2022-05-17 14:09 UTC, seia-soto commented
이후에 기준을 지금보다 명확하게 하고 본인의 의견을 반영하시고 싶으시면 직접적인 해결책을 같이 제공해주시기 바랍니다.

반복하지만 저는 이미 제 의견이 완벽하지 않다라고 생각하여서 어떻게 개선하면 좋을지 의견을 수 번 여쭈어보았습니다. 그럼에도 불구하고 협조하지 않으셔서 일시적으로 이 PR은 거부하겠습니다. 또한 이후 제 이전 주장을 근거로 한 맹목적인 PR이나 이슈를 생성하지 말아주십시오. List-KR을 더 좋은 공간으로 만들 수 있게 노력해주셔서 감사합니다. 앞으로 더 좋은 모습으로 볼 수 있도록 기대하겠습니다.

2022-05-17 14:09 UTC, closed without merging