Nongmin.com
List-KR/List-KR pull request #581
Opened 2023-01-01 16:23 UTC by green1052

2023-01-01 16:35 UTC, piquark6046 requested changes
You can block `https://www.nongmin.com/-/raw/srv-nongmin/data1/srv-nongmin/resources/pc/common/images/main_right_bnr.jpg`.

2023-01-01 16:40 UTC, green1052 commented
umm i cant think how to make good rule

2023-01-01 16:56 UTC, piquark6046 commented
You can use `*` wildcard character or regex.

2023-01-02 09:42 UTC, piquark6046 approved these changes

2023-01-02 09:42 UTC, merged