daisomall.co.kr - Ad
List-KR/List-KR pull request #587
Opened 2023-01-02 11:55 UTC by green1052

#582

2023-01-02 11:56 UTC, green1052 commented
![image](https://user-images.githubusercontent.com/34261355/210228051-bdc0823b-cffa-439a-8aae-8093dc761906.png)

2023-01-02 12:03 UTC, piquark6046 requested changes
Please discuss the following issue:
- https://github.com/List-KR/List-KR/issues/582#issuecomment-1368866767

2023-01-02 12:05 UTC, green1052 commented
what is exactly advertisement label mean?
```containing an advertisement label in the content (e.g., AD, ad, 광고)``` this?

2023-01-02 12:10 UTC, piquark6046 commented
> ```containing an advertisement label in the content (e.g., AD, ad, 광고)``` is it right?

Yes.

2023-01-02 12:11 UTC, green1052 commented
![image](https://user-images.githubusercontent.com/34261355/210229481-0c24eb11-bcef-4837-bdfd-18e37517fb0f.png)

2023-01-02 12:21 UTC, piquark6046 commented
Only that?

2023-01-02 12:24 UTC, green1052 commented
need more something?

2023-01-02 12:30 UTC, green1052 commented
the element give coupon so you think not AD?

2023-01-02 12:34 UTC, piquark6046 commented
> the element give coupon so you think not AD?

No.

Do you want to revert the following opinion in https://github.com/List-KR/List-KR/issues/582#issue-1515681356?
> 로그인 화면 보험 광고 뿐만이 아닌 메인화면 베너도 같이 차단합니다.

2023-01-02 12:45 UTC, green1052 commented
```로그인 화면 보험 광고 뿐만이 아닌 메인화면 베너도 같이 차단합니다.```를 혹시 전부 차단 해제 해달라고 생각하신건가요?

2023-01-02 12:49 UTC, green1052 commented
또한 제가 올린 해당 PR은 단순히 [로그인플러스](https://safelogin.kr)의 광고를 차단하는 규칙이며
제가 남긴 이슈에 언급했던 규칙에는 포함되어 있지 않았던 규칙입니다.

2023-01-02 12:59 UTC, piquark6046 commented
https://github.com/List-KR/List-KR/pull/587#issuecomment-1368916701
> 혹시 전부 차단 해제를 요청한 것으로 받아들이신건가요?

아니요. 단지, 저 보험 광고를 제외한 차단된 요소를 차단 해체로 받아드린 겁니다.

2023-01-02 13:04 UTC, green1052 commented
그럼 왜 이 PR을 반려하셨는지 여쭈어봐도 될까요?

- https://github.com/List-KR/List-KR/issues/582#issuecomment-1368866767
해당 부분도 광고 라벨이 없다고 하셨는데  [로그인플러스](https://safelogin.kr)에는 광고라고 명시되어 있습니다.

2023-01-02 13:14 UTC, piquark6046 commented
https://github.com/List-KR/List-KR/pull/587#issuecomment-1368929101

#587 에 대해선 반려하지 않고 기존 의견을 번복하실 것인지 여쭤본 것입니다.
그 기존 의견은 `로그인 화면 보험 광고`라고 언급하셔서 보험 배너를 광고로 판단하였을 때, 발생하는 문제에 대한 것입니다.

2023-01-02 13:21 UTC, green1052 commented
저는 보험 배너가 광고라 생각합니다.

```promoting a product or service that are not related to the actual content that a visitor wants to read/use on the website.```
해당 정책을 보면 사이트와 관련 없으며 

또한 piquark6046님깨서 단순 쿠폰을 준다는 이유로 광고라 생각하지 않으신다 하셨습니다.

https://github.com/List-KR/List-KR/pull/587#issuecomment-1368908639
>the element give coupon so you think not AD?

https://github.com/List-KR/List-KR/pull/587#issuecomment-1368910610
> the element give coupon so you think not AD?
>
> No.
>
> Do you want to revert the following opinion in https://github.com/List-KR/List-KR/issues/582#issue-1515681356?
> 로그인 화면 보험 광고 뿐만이 아닌 메인화면 베너도 같이 차단합니다.

물론 piquark6046님깨서 보험 팝업을 광고가 아니시라 생각하신다면

[로그인플러스](https://safelogin.kr) 광고만 차단해도 상관 없습니다.
해당 요소는 광고라 명시되어 있으니깐요

2023-01-02 13:53 UTC, piquark6046 commented
> 또한 보험 배너를 차단하지 않고 [로그인플러스](https://safelogin.kr/) 광고만 차단하면
무슨 문제가 발생하나요?

없습니다.

> ```promoting a product or service that are not related to the actual content that a visitor wants to read/use on the website.```
해당 정책을 보면 사이트와 관련 없으며 

정책으로는 맞는데, 부모를 `a[href^="/banner.link.php"]`로 가지는 다른 요소도 차단하시겠는지 궁금해서 그래요.

2023-01-02 13:55 UTC, green1052 commented
a[href^="/banner.link.php"]를 차단하게 되면
사이트와 관련있는 배너도 차단되기 때문에
차단하지 않는 것이 좋다고 생각합니다.

2023-01-02 13:56 UTC, green1052 commented
예를 들어
https://github.com/List-KR/List-KR/issues/582#issuecomment-1368483659

해당 부분 같이요

2023-01-03 10:56 UTC, piquark6046 approved these changes

2023-01-03 10:56 UTC, merged