jlpt.or.kr - Ad
List-KR/List-KR pull request #597
Opened 2023-01-29 00:42 UTC by liberaldev

JLPT 서울권역 홈페이지의 광고성 배너 제거.

2023-01-29 05:43 UTC, piquark6046 requested changes

2023-01-29 05:43 UTC, piquark6046 commented on filters-share/extended_css_ELEMHIDE.txt
> +jlpt.or.kr#?#tr:has(> td > a:matches-attr("href"="/\/inc\/banner_view\.php/"))+tr
No such elements found.

2023-01-29 05:43 UTC, piquark6046 commented on filters-share/specific_URL.txt
> +||jlpt.or.kr/banner/
Please move to top.

2023-01-30 12:27 UTC, liberaldev commented on filters-share/extended_css_ELEMHIDE.txt
> +jlpt.or.kr#?#tr:has(> td > a:matches-attr("href"="/\/inc\/banner_view\.php/"))+tr
![jlptorkr](https://user-images.githubusercontent.com/56965274/215475703-4b4e675b-2838-447d-ba9c-6a788dd1f70c.png)

개발자 도구를 살펴보면 이러한 요소가 분명히 존재합니다. `/inc/banner_view.php`로 시작하는 링크인데 이것은 하나같이 광고성 링크라는 점입니다. 또한 해당 사이트는 각 칸을 띄우기 위해서 하나의 tr을 추가하는 식으로 사용하는데 두 번째 줄은 이에 대응하는 것입니다.

참고로 해당 사이트는 옛날에 만들어진 사이트라 플렉스나 그리드를 쓰는게 아닌 테이블로 레이아웃을 짠 케이스라 `jlpt.or.kr#?#tr:has(a:matches-attr("href"="/\/inc\/banner_view\.php/"))` 식으로 할 경우 사이트가 아예 소멸됩니다.

2023-01-30 12:31 UTC, piquark6046 commented on filters-share/extended_css_ELEMHIDE.txt
> +jlpt.or.kr#?#tr:has(> td > a:matches-attr("href"="/\/inc\/banner_view\.php/"))+tr
그건 아는데요.
`:matches-css` 확장된 attribute을 사용하지 않고도, `tr:has(> td > a[href^="/inc/banner_view.php"])`으로 작성할 수 있어요. 게다가 `:has`는 아직 Mozilla Firefox에서 지원을 안하지 대부분의 메이저 웹 브라우저에서 지원하고요.

또한, 단순 웹 요청 차단 규칙으로 해결할 수 있는 문제이예요.

2023-01-30 13:29 UTC, liberaldev commented on filters-share/specific_URL.txt
> +||jlpt.or.kr/banner/
맨 위로 올렸습니다.

2023-01-30 13:30 UTC, piquark6046 requested changes

2023-01-30 13:30 UTC, piquark6046 commented on filters-share/extended_css_ELEMHIDE.txt
> +jlpt.or.kr#?#tr:has(> td > a[href^="/inc/banner_view.php"])+tr
삭제해주세요.

2023-01-30 13:38 UTC, liberaldev commented on filters-share/extended_css_ELEMHIDE.txt
> +jlpt.or.kr#?#tr:has(> td > a[href^="/inc/banner_view.php"])+tr
삭제했습니다. 깔금하게 요소(element)까지 차단하고 싶어서 넣은 코드인데 이 코드가 없어도 작동은 되네요. 물론 이웃한 5픽셀짜리 tr태그까지 삭제는 못하지만 그렇게 영향을 미치지는 않고요.

2023-01-30 13:38 UTC, piquark6046 approved these changes

2023-01-30 13:39 UTC, merged