acmicpc.net - Ad
List-KR/List-KR pull request #667
Opened 2023-04-03 05:00 UTC by Taewan-P

URL Pattern in [https://www.acmicpc.net/status](https://www.acmicpc.net/status)
<img width="583" alt="image" src="https://user-images.githubusercontent.com/27392567/229415341-97cee89d-c26e-4d0b-8c1d-0d6a73400be8.png">

Removes the top banner

<img width="1011" alt="image" src="https://user-images.githubusercontent.com/27392567/229415475-1e721cd9-bf5a-4278-9dcd-63baa2283435.png">

2023-04-03 10:28 UTC, piquark6046 requested changes
Please update the version to `2023.0403.1`.

2023-04-03 10:37 UTC, piquark6046 approved these changes

2023-04-03 10:37 UTC, merged

2023-04-05 11:26 UTC, wider93 commented
This removes most images uploaded in BOJ. Should be reverted.
eg) https://boj.kr/25793

2023-04-05 11:44 UTC, piquark6046 commented
@wider93 Resolved.